#! /bin/sh

if [ -z "$1" ] ; then
	echo "请选择代码分支"
	exit 0
else
  echo "添加本地改动到本地仓库"
  git add .
  git commit -m "on local server"

  echo "更新代码至本地仓库"
  git pull origin master

  echo "运行数据库迁移"
  rake db:migrate

  echo "重启NGINX服务器, 请输入ROOT权限密码"
  sudo /opt/nginx/sbin/nginx -s reload

  exit 0
fi
